// src/views/link/link.vue
<template>
  <div class="wrapper">
    <h2 class="content-title">友情链接列表</h2>
    <div class="box-table">
      <my-form :ref="searchForm.ref" :formConfig="searchForm"></my-form>
      <my-table
        :tableData="tableData"
        :pageObj="pageObj"
        @sortChange="sortChange"
        @pageChange="pageChange"
      ></my-table>
    </div>
    <el-dialog
      :title="dialogBox.isEdit ? '编辑友情链接' : '新增友情链接'"
      :visible.sync="dialogBox.boxShow"
      width="640px"
    >
      <my-form :ref="linkForm.ref" :formConfig="linkForm">
        <el-color-picker slot='color' v-model="linkForm.formModel.color"></el-color-picker>
      </my-form>
      <div slot="footer" class="dialog-footer">
        <el-button @click="dialogBox.boxShow = false">取 消</el-button>
        <el-button type="primary" @click="confirSubmit">确 定</el-button>
      </div>
    </el-dialog>
  </div>
</template>

<style scoped lang="scss"></style>

<script>
import MyTable from "@/components/MyTable";
import MyForm from "@/components/MyForm";
import Format from "@/utils/format.js";
export default {
  data() {
    return {
      sortObj: {
        sortBy: null,
        sortOrders: null
      },
      dialogBox: {
        boxShow: false,
        isEdit: false,
        detailItem: {}
      },
      searchForm: {
        labelWidth: "70px",
        ref: "searchRef",
        inline: true,
        marginRight: "30px",
        formItemList: [
          {
            type: "text",
            prop: "name",
            width: "180px",
            label: "链接名称",
            placeholder: "链接名称",
            blur: this.getDataList
          }
        ],
        operate: [
          {
            name: "新增",
            hide: false,
            handleClick: this.dataAdd
          }
        ],
        formModel: {
          name: ""
        }
      },
      pageObj: {
        pageSize: 10,
        total: 0,
        currentPage: 1
      },
      tableData: {
        ref: "table",
        dataList: [],
        columns: [
          {
            prop: "name",
            sortable: "custom",
            label: "链接名称"
          },
          {
            prop: "linkAddress",
            label: "链接地址",
            showTooltip: true
          },
          {
            prop: 'color',
            label: '链接颜色',
            render: (h, params)=>{
              return h('div',{
                style: {
                  width: '120px',
                  height: '20px',
                  margin: '0 auto',
                  background: params.row.color
                }
              })
            }
          },
          {
            prop: "createTime",
            sortable: "custom",
            label: "创建时间",
            render: (h, params) => {
              let time = params.row.createTime?params.row.createTime.split(' ')[0]:'--'
              return h('div', time)
            }
          },
          {
            prop: "operate",
            align: "center",
            label: "操作",
            render: (h, params) => {
              return h(
                "div",
                {
                  style: {
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center"
                  }
                },
                [
                  h(
                    "el-button",
                    {
                      props: {
                        type: "primary",
                        size: "small"
                      },
                      style: {
                        display: this.authList.includes('5e834faffb69305aa091e831')?'block':'none'
                      },
                      on: {
                        click: () => {
                          this.dialogBox.detailItem = params.row;
                          this.editData(params);
                        }
                      }
                    },
                    "编辑"
                  ),
                  h(
                    "el-button",
                    {
                      props: {
                        type: "danger",
                        size: "small"
                      },
                      style: {
                        display: this.authList.includes('5e834fb5fb69305aa091e832')?'block':'none'
                      },
                      on: {
                        click: () => {
                          this.dataDel(params);
                        }
                      }
                    },
                    "删除"
                  )
                ]
              );
            }
          }
        ]
      },
      linkForm: {
        labelWidth: "80px",
        ref: "linkRef",
        labelPosition: "right",
        marginRight: "10px",
        formItemList: [
          {
            type: "text",
            prop: "name",
            width: "450px",
            label: "链接名称",
            placeholder: "请输入链接名称"
          },
          {
            type: "text",
            prop: "linkAddress",
            width: '450px',
            label: "链接地址",
            placeholder: "请输入链接地址"
          },
          {
            slot: "color",
            prop: "color",
            width: '450px',
            label: "链接颜色"
          }
        ],
        formModel: {
          name: '',
          linkAddress: '',
          color: '#409EFF'
        },
        rules: {
          name: [
            {
              required: true,
              validator: Format.FormValidate.Form("链接名称").NoEmpty,
              trigger: "blur"
            },
          ],
          linkAddress: [
            {
              required: true,
              validator: Format.FormValidate.Form("链接地址").NoEmpty,
              trigger: "blur"
            },
          ],
          color: [
            { required: true, validator: Format.FormValidate.Form('链接颜色').TypeSelect, trigger: 'change' }
          ]
        }
      }
    };
  },
  created() {
    this.searchForm.operate[0].hide = !this.authList.includes('5e834f9efb69305aa091e830')
    this.tableData.columns[4].hide = !this.authList.includes('5e834faffb69305aa091e831') && !this.authList.includes('5e834fb5fb69305aa091e832')
  },
  mounted() {
    this.getDataList();
  },
  methods: {
    // 数据列表查询
    getDataList(page) {
      let pageObj = this.pageObj;
      pageObj.currentPage = page === true ? pageObj.currentPage : 1;
      let formModel = this.searchForm.formModel;
      let { sortBy, sortOrders } = this.sortObj;
      this.$api.link
        .linkList({
          currentPage: pageObj.currentPage,
          pageSize: pageObj.pageSize,
          name: formModel.name,
          sortBy,
          sortOrders
        })
        .then(res => {
          let code = res.code;
          if (code === this.$constant.reqSuccess) {
            this.pageObj.total = res.data.count;
            this.tableData.dataList = res.data.data;
          } else {
            this.$message.warning("获取友情链接列表失败");
          }
        });
    },
    sortChange(data) {
      if (data.order) {
        this.sortObj = {
          sortBy: data.prop,
          sortOrders: data.order
        };
      } else {
        this.sortObj = {
          sortBy: null,
          sortOrders: null
        };
      }
      this.getDataList();
    },
    dataAdd() {
      if (this.$refs["linkRef"]) {
        this.$refs["linkRef"].$refs["linkRef"].resetFields();
      }
      this.dialogBox.isEdit = false;
      this.dialogBox.boxShow = true;
    },
    //编辑数据表单赋值
    editData(params) {
      this.dialogBox.isEdit = true;
      this.dialogBox.boxShow = true;
      this.$nextTick(() => {
        if (this.$refs["linkRef"]) {
          this.$refs["linkRef"].$refs["linkRef"].resetFields();
        }
        this.linkForm.formModel = {
          name: params.row.name,
          linkAddress: params.row.linkAddress,
          color: params.row.color
        };
      })
    },
    // 新增或编辑数据
    confirSubmit() {
      this.$refs["linkRef"].$refs["linkRef"].validate(valid => {
        let dialogBox = this.dialogBox;
        let formModel = this.linkForm.formModel;
        if (valid) {
          if (dialogBox.isEdit) {
            this.$api.link
              .linkUpdate({
                id: dialogBox.detailItem._id,
                name: formModel.name,
                linkAddress: formModel.linkAddress,
                color: formModel.color
              })
              .then(res => {
                let code = res.code;
                if (code === this.$constant.reqSuccess) {
                  this.dialogBox.boxShow = false;
                  this.getDataList();
                  this.$message.success("友情链接信息更新成功");
                } else if (code === this.$constant.dataAlready) {
                  this.$message.warning("链接名称已存在");
                  formModel.name = "";
                } else {
                  this.$message.warning("友情链接更新失败");
                }
              });
          } else {
            this.$api.link
              .linkAdd({
                name: formModel.name,
                linkAddress: formModel.linkAddress,
                color: formModel.color
              })
              .then(res => {
                let code = res.code;
                if (code === this.$constant.reqSuccess) {
                  this.dialogBox.boxShow = false;
                  this.getDataList();
                  this.$message.success("友情链接信息添加成功");
                } else if (code === this.$constant.dataAlready) {
                  this.$message.warning("链接名称已存在");
                  formModel.name = "";
                } else {
                  this.$message.warning("友情链接信息添加失败");
                }
              });
          }
        } else {
          this.$message.warning("信息校验失败");
        }
      });
    },
    dataDel(params) {
      this.$confirm("此操作将删除该友情链接, 是否继续?", "提示", {
        confirmButtonText: "确定",
        cancelButtonText: "取消",
        type: "warning"
      })
        .then(() => {
          this.$api.link.linkDel(params.row._id).then(res => {
            let code = res.code;
            if (code === this.$constant.reqSuccess) {
              this.getDataList();
              this.$message.success("友情链接删除成功");
            } else {
              this.$message.warning("友情链接删除失败");
            }
          });
        })
        .catch(() => {});
    },
    // 分页页数改变
    pageChange(page) {
      this.pageObj.currentPage = page;
      this.getDataList(true);
    }
  },
  components: {
    MyTable,
    MyForm
  },
  computed: {
    authList(){
      return this.$store.getters.getAuthList
    }
  }
};
</script>

// src/pages/link/index.tsx
import React, { useState, useEffect } from "react";
import { Form, Input, Button, message, Space, Table, Modal } from 'antd';
import { connect } from 'react-redux'
import { StoreState } from '@/store/types'
import api from '@/api/index';
import { constantData } from '@/utils/utils';
import { FormValidate } from '@/utils/format';
import InputColor from 'react-input-color';

const Link = (props: any) => {
  const { confirm } = Modal;
  const [searchForm] = Form.useForm();
  const [modalForm] = Form.useForm();
  let userInfo = props.stateData.userInfo;
  let [tableData, setTableData] = useState<any[]>([])
  let [initialColor, setInitialColor] = useState('#5e72e4')
  let [selectColor, setSelectColor] = useState<any>({})
  let [modalObj, setModalObj] = useState<any>({
    title: '',
    visible: false,
    loading: false,
    selectRow: {}
  })
  let [pageObj, setPageObj] = useState({
    pageSize: 10,
    total: 0,
    currentPage: 1
  })
  let [sortObj, setSortObj] = useState({
    sortBy: '',
    sortOrders: ''
  })

  let tableColumns = [
    {
      title: '链接名称',
      sorter: true,
      align: 'center' as 'center',
      dataIndex: 'name'
    },
    {
      title: '链接地址',
      align: 'center' as 'center',
      ellipsis: true,
      dataIndex: 'linkAddress',
      render: (text:string, record:any) => (
        <span>
          {text || '--'}
        </span>
      )
    },
    {
      title: '链接颜色',
      align: 'center' as 'center',
      dataIndex: 'color',
      render: (text:string, record:any) => (
        <div style={{width: '120px', height: '20px', margin: '0 auto', backgroundColor: text}}>
        </div>
      )
    },
    {
      title: '创建时间',
      sorter: true,
      align: 'center' as 'center',
      dataIndex: 'createTime'
    },
    {
      title: '操作',
      align: 'center' as 'center',
      dataIndex: 'operate',
      render: (text:string, record:any) => (
        <Space size='large'>
          {
            userInfo.roleId.functionList.includes('5e834faffb69305aa091e831')?
            <Button type='primary' onClick={()=>editLink(record)}>编辑</Button>:''
          }
          {
            userInfo.roleId.functionList.includes('5e834fb5fb69305aa091e832')?
            <Button type="primary" onClick={()=>linkRemove(record._id)} danger>删除</Button>:''
          }
        </Space>
      )
    }
  ]

  useEffect(() => {
    getDataList()
  }, []);

  // 获取列表数据
  const getDataList = (page?: Boolean)=>{
    pageObj.currentPage = page === true?pageObj.currentPage:1;
    let formModel = searchForm.getFieldsValue();
    let sortOrders = '';
    if(sortObj.sortOrders){
      if(sortObj.sortOrders === 'ascend'){
        sortOrders = '1';
      }else{
        sortOrders = '0';
      }
    }
    api.link.linkList({
      currentPage: pageObj.currentPage,
      pageSize: pageObj.pageSize,
      name: formModel.name,
      sortBy: sortObj.sortBy,
      sortOrders
    }).then(res =>{
      let code = res.data.code
      if(code === constantData.reqSuccess){
        pageObj.total = res.data.data.count;
        setPageObj({...pageObj})
        setTableData([...res.data.data.data])
      }else{
        message.warning('获取链接列表失败');
      }
    })
  }
  // table排序分页变化
  const tableChange = (pagination:any, filters:any, sorter:any) =>{
    if(pageObj.currentPage !== pagination.current || pageObj.pageSize !== pagination.pageSize){
      pageObj.currentPage = pagination.current;
      pageObj.pageSize = pagination.pageSize;
      setPageObj({...pageObj})
      getDataList(true)
    }
    if(JSON.stringify(sorter) !== '{}'){
      if(sorter.field !== sortObj.sortBy || sorter.order !== sortObj.sortOrders){
        sortObj.sortBy = sorter.order?sorter.field:'';
        sortObj.sortOrders = sorter.order?sorter.order:'';
        setSortObj({...sortObj})
        getDataList()
      }
    }
  }
  // 友情链接删除
  const linkRemove = (id:string)=>{
    confirm({
      title: '提示',
      content: '此操作将删除该友情链接, 是否继续?',
      closable: true,
      okType: 'danger',
      onOk() {
        return new Promise((resolve, reject) => {
          api.link.linkDel(id).then((res)=>{
            let code = res.data.code;
            resolve('')
            if(code === constantData.reqSuccess){
              getDataList();
              message.success('友情链接删除成功');
            }else{
              message.warning('友情链接删除失败');
            }
          })
        }).catch(() => {});
      }
    });
  }
  // 友情链接新增
  const linkAdd = ()=>{
    modalObj.title = '新增友情链接';
    modalObj.selectRow = {};
    modalObj.visible = true;
    setModalObj({...modalObj})
  }
  // 编辑打开弹框
  const editLink = (row:any)=>{
    modalObj.title = '编辑友情链接';
    modalObj.selectRow = row;
    modalObj.visible = true;
    modalForm.setFieldsValue({ 
      name: row.name,
      linkAddress: row.linkAddress
    })
    setInitialColor(row.color)
    setModalObj({...modalObj})
  }
  // 新增或编辑提交
  const modalConfir = ()=>{
    modalForm.validateFields().then((values)=>{
      modalObj.loading = true;
      setModalObj({...modalObj})
      if(modalObj.selectRow._id){
        api.link.linkUpdate({
          id: modalObj.selectRow._id,
          name: values.name,
          linkAddress: values.linkAddress,
          color: selectColor.hex || initialColor
        }).then((res)=>{
          let code = res.data.code
          modalObj.loading = false;
          if(code === constantData.reqSuccess){
            modalObj.visible = false;
            getDataList();
            message.success('友情链接信息更新成功');
          }else if(code === constantData.dataAlready){
            message.warning('友情链接名称已存在');
            modalForm.setFieldsValue({ 
              name: ''
            })
          }else{
            message.warning('友情链接信息更新失败');
          }
          setModalObj({...modalObj})
        })
      }else{
        api.link.linkAdd({
          name: values.name,
          linkAddress: values.linkAddress,
          color: selectColor.hex || initialColor
        }).then((res)=>{
          let code = res.data.code
          modalObj.loading = false;
          if(code === constantData.reqSuccess){
            modalObj.visible = false;
            getDataList();
            modalForm.resetFields();
            message.success('友情链接信息添加成功');
          }else if(code === constantData.dataAlready){
            message.warning('友情链接名称已存在');
            modalForm.setFieldsValue({ 
              name: ''
            })
          }else{
            message.warning('友情链接信息添加失败');
          }
          setModalObj({...modalObj})
        })
      }
    }).catch(()=>{});
  }
  // 关闭弹框
  const modalCancel = ()=>{
    modalObj.visible = false;
    setInitialColor('#5e72e4')
    modalForm.resetFields();
    setModalObj({...modalObj})
  }

  return <div className='link-wrapper'>
    <h2 className='content-title'>友情链接管理</h2>
    <div className="box-table">
      <Form
        layout='inline'
        form={searchForm}
      >
        <Form.Item label="链接名称" name='name' className='margin-bottom-20'>
           <Input 
            maxLength={20} 
            allowClear={true}
            onBlur={()=>{getDataList()}} 
            placeholder="链接名称" 
          />
        </Form.Item>
        <Form.Item className='margin-left-30 margin-bottom-20'>
           {
             userInfo.roleId.functionList.includes('5e834f9efb69305aa091e830')?<Button type="primary" onClick={linkAdd}>新增</Button>:''
           }
        </Form.Item>
      </Form>
      <div className="table-show">
        <Table rowKey='_id' columns={tableColumns} dataSource={tableData} pagination={{
          total: pageObj.total,
          showTotal: ()=>`共 ${pageObj.total} 条`,
          current: pageObj.currentPage,
          pageSize: pageObj.pageSize,
        }} onChange={tableChange} />
      </div>
    </div>
    <Modal className='modal-height' title={modalObj.title}  maskClosable={false} confirmLoading={modalObj.loading} visible={modalObj.visible} onOk={modalConfir} onCancel={modalCancel}>
    <Form
        form={modalForm}
        validateTrigger='onBlur'
        requiredMark={false}
        scrollToFirstError
      >
        <Form.Item
          name="name"
          label="链接名称"
          rules={FormValidate({name: '链接名称'})}
        >
          <Input 
            maxLength={20} 
            allowClear={true} 
            placeholder="链接名称" 
          />
        </Form.Item>
        <Form.Item
          name="linkAddress"
          label="链接地址"
          rules={FormValidate({name: '链接地址'})}
        >
          <Input  
            allowClear={true} 
            placeholder="链接地址" 
          />
        </Form.Item>
        <Form.Item
          name="color"
          label="链接颜色"
        >
          <InputColor initialValue={initialColor} onChange={setSelectColor} />
        </Form.Item>
      </Form>
    </Modal>
  </div>;
};

const mapStateToProps = (state: StoreState) => ({
  stateData: state
})

export default connect(mapStateToProps)(Link)
